apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    end: back
spec:
  replicas: 2
  selector:
    matchLabels:
      end: back
  template:
    metadata:
      labels:
        end: back
    spec:
      containers:
      - name: borodun-back-container
        image: borodun/back
        ports:
        - containerPort: 9999
        env:
          - name: LOGIN
            value: "$(LOGIN)"
          - name: PASSWORD
            value: "${PASSWORD}"
          - name: ACCESSKEY
            value: $(ACCESSKEY)
          - name: SECRETKEY
            value: ${SECRETKEY}


