apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: NodePort
  selector:
    end: back
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 32223  
